import './globals.css';
import Navbar from './components/basic/Navbar/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        {children}
        <Navbar />
      </body>
    </html>
  );
}
